# Generated by Django 2.2.6 on 2019-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
