# Generated by Django 2.2.6 on 2019-11-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0003_auto_20191121_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
