# Generated by Django 2.2.6 on 2019-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0006_auto_20191125_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
