# Generated by Django 2.2.6 on 2019-12-03 19:31

from django.db import migrations
import trix.fields


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0007_auto_20191201_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=trix.fields.TrixField(),
        ),
    ]
