# Generated by Django 2.2.6 on 2019-12-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0009_auto_20191203_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
